### ISSUE TITLE
关于您的数据库的结构和内容能发布一下吗，没有您的数据库的信息，没法运行和使用您的系统

### ISSUE THREAD

**Issue by imling** [JX-Chenghao/SecondhandOnCampus#6]
想通过您的网站来学习一下ssm框架和网站的结构设计与实现，可惜没有数据库内容，运行不了，我也尝试根据您的数据库映射文件里的信息来构建数据库，但是遇到了很多问题，图片无法读取，还有一些功能也无法正常使用，管理员后台部分也不能进入，希望您能发布下数据库文件，sql文件，如果可以的 话，我将万分感谢

**Comment by JX-Chenghao** [comment]
ok,已上传
